@startuml
node UE渲染客户端实例1
node 信令服务器1
node UE渲染客户端实例2
node 信令服务器2
node 匹配服务器
node Web服务器
actor 用户1
actor 用户2
actor 用户3

UE渲染客户端实例1 -- 信令服务器1
信令服务器1 -- 匹配服务器
UE渲染客户端实例2 -- 信令服务器2
信令服务器2 -- 匹配服务器
用户1 -- Web服务器
用户2 -- Web服务器
用户3 -- Web服务器
用户1 -- 匹配服务器
用户2 -- 匹配服务器
用户3 -- 匹配服务器
@enduml